# Generated by Django 2.1 on 2018-08-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('method', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=32)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=6)),
                ('remarks', models.CharField(max_length=64)),
            ],
        ),
    ]
